sudo: required

language: bash

dist: trusty

services:
  - docker

script:
  - docker build -f Dockerfile . -t atomxorg/arch-linux:kernel
  - echo "$password" | docker login -u "atomxorg" --password-stdin
  - docker push atomxorg/arch-linux:kernel
