sudo: required

language: bash

services:
  - docker

script:
  - make ci-test
  - docker build -f Dockerfile . -t panchajanya1999/archlinux:latest
  - echo "86abc7fb-21f7-4d31-a622-baf52d49f41f" | docker login -u "panchajanya1999" --password-stdin
  - docker push panchajanya1999/archlinux
