sudo: required

language: bash

dist: trusty

services:
  - docker

script:
  - docker build -f Dockerfile . -t AtomX/archlinux:latest
  - echo "$password" | docker login -u "AtomX" --password-stdin
  - docker push AtomX/archlinux:latest
