--- 
jobs: 
  compile: 
    docker: 
      - 
        image: panchajanya1999/archlinux
    steps: 
      - 
        run: 
          command: |
              git clone --depth 1 https://github.com/Panchajanya1999/archlinux-docker.git
              cd archlinux-docker
              pacman -S --noconfirm docker
              systemctl start docker.service
              systemctl enable docker.service
              make ci-test
              docker build -f Dockerfile . -t panchajanya1999/archlinux:latest
              echo "$password" | docker login -u "panchajanya1999" --password-stdin
              docker push panchajanya1999/archlinux:latest
version: 2.1
workflows: 
  cooking: 
    jobs: 
      - compile
  version: 2.1
